--- #YAML:1.0
name: WWW::Folksonomy
abstract: A Folksonomy schema and API from Perl
version: 0.03
author:
  - Todd Harris <info@toddharris.net>
license: perl
distribution_type: module
requires:
  Class::DBI: 0
  DBI: 0
build_requires:
  Test: 0
urls:
   license: http://toddot.net/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Module::Build version 0.20
